# Generated by Django 4.1.7 on 2023-04-08 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('pno', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('securityQues', models.TextField(max_length=50)),
                ('securityAns', models.TextField(max_length=50)),
                ('bio', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
