# Generated by Django 4.1.7 on 2023-04-08 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserTrips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserDetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.JSONField(default=list)),
                ('gender', models.JSONField(default=list)),
                ('maritalStatus', models.JSONField(default=list)),
                ('travelFrequency', models.JSONField(default=list)),
                ('tripType', models.JSONField(default=list)),
                ('budget', models.JSONField(default=list)),
                ('travelCompanion', models.JSONField(default=list)),
                ('communicationStyle', models.JSONField(default=list)),
                ('interests', models.JSONField(default=list)),
                ('kindOfTrips', models.JSONField(default=list)),
                ('travelDestination', models.JSONField(default=list)),
                ('stays', models.JSONField(default=list)),
                ('travelMotivation', models.JSONField(default=list)),
                ('requirement', models.JSONField(default=list)),
                ('modeOfTravel', models.JSONField(default=list)),
                ('travelPace', models.JSONField(default=list)),
                ('eatingPlaces', models.JSONField(default=list)),
                ('accomodations', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
