# Generated by Django 4.1.7 on 2023-04-10 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserTrips', '0004_alter_preferences_user_alter_userdetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavingFrom', models.CharField(max_length=20)),
                ('goingTo', models.CharField(max_length=20)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('noOfPersons', models.IntegerField()),
                ('noOfDays', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishedtrips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
