# Generated by Django 4.1.7 on 2023-04-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTrips', '0006_remove_publishedtrips_noofdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
